package com.example.demo.entity;

import java.util.Date;

public class passenger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.id_type
     *
     * @mbggenerated
     */
    private Integer idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.discount_type
     *
     * @mbggenerated
     */
    private Integer discountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.verify_status
     *
     * @mbggenerated
     */
    private Integer verifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passenger_0.del_flag
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.id
     *
     * @return the value of t_passenger_0.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.id
     *
     * @param id the value for t_passenger_0.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.username
     *
     * @return the value of t_passenger_0.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.username
     *
     * @param username the value for t_passenger_0.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.real_name
     *
     * @return the value of t_passenger_0.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.real_name
     *
     * @param realName the value for t_passenger_0.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.id_type
     *
     * @return the value of t_passenger_0.id_type
     *
     * @mbggenerated
     */
    public Integer getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.id_type
     *
     * @param idType the value for t_passenger_0.id_type
     *
     * @mbggenerated
     */
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.id_card
     *
     * @return the value of t_passenger_0.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.id_card
     *
     * @param idCard the value for t_passenger_0.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.discount_type
     *
     * @return the value of t_passenger_0.discount_type
     *
     * @mbggenerated
     */
    public Integer getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.discount_type
     *
     * @param discountType the value for t_passenger_0.discount_type
     *
     * @mbggenerated
     */
    public void setDiscountType(Integer discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.phone
     *
     * @return the value of t_passenger_0.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.phone
     *
     * @param phone the value for t_passenger_0.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.create_date
     *
     * @return the value of t_passenger_0.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.create_date
     *
     * @param createDate the value for t_passenger_0.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.verify_status
     *
     * @return the value of t_passenger_0.verify_status
     *
     * @mbggenerated
     */
    public Integer getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.verify_status
     *
     * @param verifyStatus the value for t_passenger_0.verify_status
     *
     * @mbggenerated
     */
    public void setVerifyStatus(Integer verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.create_time
     *
     * @return the value of t_passenger_0.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.create_time
     *
     * @param createTime the value for t_passenger_0.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.update_time
     *
     * @return the value of t_passenger_0.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.update_time
     *
     * @param updateTime the value for t_passenger_0.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passenger_0.del_flag
     *
     * @return the value of t_passenger_0.del_flag
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passenger_0.del_flag
     *
     * @param delFlag the value for t_passenger_0.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}