package com.example.demo.entity;

import java.util.Date;

public class userPhone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.deletion_time
     *
     * @mbggenerated
     */
    private Long deletionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone_0.del_flag
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.id
     *
     * @return the value of t_user_phone_0.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.id
     *
     * @param id the value for t_user_phone_0.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.username
     *
     * @return the value of t_user_phone_0.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.username
     *
     * @param username the value for t_user_phone_0.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.phone
     *
     * @return the value of t_user_phone_0.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.phone
     *
     * @param phone the value for t_user_phone_0.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.deletion_time
     *
     * @return the value of t_user_phone_0.deletion_time
     *
     * @mbggenerated
     */
    public Long getDeletionTime() {
        return deletionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.deletion_time
     *
     * @param deletionTime the value for t_user_phone_0.deletion_time
     *
     * @mbggenerated
     */
    public void setDeletionTime(Long deletionTime) {
        this.deletionTime = deletionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.create_time
     *
     * @return the value of t_user_phone_0.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.create_time
     *
     * @param createTime the value for t_user_phone_0.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.update_time
     *
     * @return the value of t_user_phone_0.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.update_time
     *
     * @param updateTime the value for t_user_phone_0.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone_0.del_flag
     *
     * @return the value of t_user_phone_0.del_flag
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone_0.del_flag
     *
     * @param delFlag the value for t_user_phone_0.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}