package com.example.demo.mapper;

import com.example.demo.entity.passenger;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface passengerMapper {
    List<passenger> select(String username);
    int insertpassenger(passenger passenger);
    int update(passenger passenger);
    int remove(passenger passenger);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    int insert(passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    int insertSelective(passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    passenger selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passenger_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(passenger record);
}