package com.example.demo.mapper;

import com.example.demo.entity.t_user_0;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface t_user_0Mapper {
List<t_user_0> selrctAA();
    t_user_0 login(t_user_0 user);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    int insert(t_user_0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    int insertSelective(t_user_0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    t_user_0 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_user_0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_user_0 record);
}