package com.example.demo.mapper;

import com.example.demo.entity.userMail;

public interface userMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    int insert(userMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    int insertSelective(userMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    userMail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(userMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_mail_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(userMail record);
}