package com.example.demo.mapper;

import com.example.demo.entity.userPhone;

public interface userPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    int insert(userPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    int insertSelective(userPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    userPhone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(userPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_phone_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(userPhone record);
}